source/_locales/en/messages.json, source/_locales/fr/messages.json, source/js/background.js, source/options/options.html
Fixes #25
Also button message now localized
Pas vraiment le temps de tester, mais j’espère que c'est bon ! :smile:
=> Add the option to disable "Share on (Better) TweetDeck" button

source/_locales/de/messages.json
I have corrected some translations to be coherent with what the user would see in their browser's UI (e.g. "Extension" → "Erweiterung"), fixed some typos, and an inconsistency with the polite form. I have also translated some untranslated strings and added strings that were not present in this file compared to the English one (lines 172 & 207).  
Furthermore, I have changed some strings following the "it sounds better" motto (e.g. line 92). I do realise that this is subject to personal opinion, and hope that I'm not stepping on anyone's toes, especially the original translator's.
=> Updated German translation

source/_locales/en/messages.json
Replaced the single quotes by double quotes.
Fix typo on "contexctual".
Remove end of line whitespaces. (Add that in your sublime-prefs for the love of god: "trim_trailing_white_space_on_save": true)
=> Fix quotes and contexctual

source/_locales/de/messages.json
Applies fixes from #30 to German translation
=> Fix quotes and trailing spaces in German translation

source/_locales/en/messages.json, source/js/content.js, source/options/options.html
=> Apply RTL style to rtl languages texts

src/css/index.css
I see your recent update for v3, seems pretty cool!
Just sharing my little change to minimise scroll bar without delete it.
What do you think about this?
:heart:
=> Minimal scroll bars!

src/css/features/show-verified.css
Alignement and background fixes
* **Alignement**
Avoid too much pic overriding
* **Background**
Fix the missing pixel in the background ![image](https://cloud.githubusercontent.com/assets/846943/17700671/14847372-63c7-11e6-81ee-40dd9a033a55.png)
Before:
After:
With round pic:
=> fix verified badge

CONTRIBUTING.md
This pull request adds a section to the contribution guidelines detailing the process of adding a new feature or fixing bugs and submitting them to the main repository!
=> Added contribution guidelines for adding features or bugfixes

meta/ja_desc.md, src/_locales/ja/messages.json
Hello, I translated messages for Japanese users. Could you marge these? Thank you.
=> 🇯🇵 add ja locale

src/_locales/en/messages.json, src/js/background.js, src/js/inject.js, src/options/options.html
Second time's the charm.
Improved to not revert any other experiments, but can be easily extended to do so.
=> Revert to old search

package.json, src/_locales/en/messages.json, src/js/background.js, src/js/inject.js, src/js/util/browserHelper.js, src/options/options.html
I did this in phpstorm, when I ran `npm run test` it generated an incredible amount of errors and I'm going to attribute that to me being on npm8 / windows.
I fixed the obvious eslint issues that the editor pointed out to me with what it picked up from the .eslintrc* but other things may not have been detected properly.
The helper functions might be a bit out of place and the selectors might be a bit funky looking but getMedia works better than it did in my userscript thanks to the structure of BTD.
=> Added hotlink action item.

src/css/index.css, src/js/content.js, src/js/inject.js
- the mentions are like before in the column
- I have trouble restoring them in the small composer box in columns, messing with the max-height of this box completely breaks the close/opening interaction for some reason (but modifying the value in the DevTools works though...)
=> Bring back old replies

src/js/inject.js
=> :wrench: made it so downloaded images / gifs use the right username

src/_locales/en/messages.json, src/js/background.js, src/js/content.js, src/js/inject.js, src/options/options.html, src/options/options.js
this is what was actually meant to solve the second part of #200
=> Allow file name formats to be specified for downloaded files

gulpfile.babel.js, src/js/util/logger.js
imagine: click on error, find the error
we are in a future civilization, truly
=> Log doesn't get drowned in Verbose messages, sourcemaps correct.

src/_locales/en/messages.json, src/js/background.js, src/js/inject.js, src/options/options.html
If you like them so much then why don't you FOLLOW them, huh?!
=> Option to follow users upon ctrl+interacting with their tweets.

package-lock.json, package.json
=> Add husky for prepush linting hook

src/js/util/webcrack.js
=> Added in webcrack.

.idea/codeStyleSettings.xml, .idea/cssdialects.xml, .idea/inspectionProfiles/Project_Default.xml, .idea/jsLibraryMappings.xml, .idea/watcherTasks.xml
97% less likely to try and beat up code errantly
=> IDE: made more consistent with .eslintrc & project style

config/default.js, src/js/background.js, src/js/content.js, src/js/util/browserHelper.js
for some reason modifying config/*.js doesn't reflect so i'm chalking
it up to being cursed :snowman:
=> Alert users that they may be running multiple BTD extensions.

gulpfile.babel.js, package.json, src/js/background.js, tools/manifests/common.js
you can also press `ctrl+shift+e` to do it
=> BTD icon lights up & reloads extension + TD pages in dev mode

src/_locales/en/messages.json, src/js/background.js, src/js/inject.js, src/options/options.html, src/options/options.js
a side effect of this is that select dropdowns work 
@eramdam this PR has a change in it that resolves vestigial changes from making alt+click handle context quoting
(dupe because apparently renaming my local branch caused the old one to be shut)
=> option to use follow dialog instead of column owner on ctrl+interact

src/_locales/en/messages.json, src/js/background.js, src/js/inject.js, src/options/options.html
=> you can decide if you want to pause&collapse and unpause&uncollapse now

src/_locales/en/messages.json, src/js/background.js, src/js/inject.js, src/options/options.html
=> Edit tweets for real this time

src/_locales/en/messages.json, src/js/inject.js, src/options/options.html
- added big disclaimer on the edit feature
- edited tweets will no longer appear with html entities in them
see comments on: #243
=> edit button just as dangerous, installed more signs

src/js/inject.js, src/js/util/ame.js
=> Add filter in AME: mute of a specific tweet

src/_locales/en/messages.json, src/_locales/ja/messages.json, src/js/content.js, src/js/util/keepHashtags.js, src/options/options.html
Keep tweeted hashtags in tweet textarea.
This is useful when user want to tweet using same hastags many times 
This run like this.
https://i.imgur.com/7V8ZLIH.gif
=> Keep tweeted hashtags

src/_locales/ja/messages.json
Changed Japanese translations to more natural expression🗾
=> 🌐 minor Japanese translation change

package-lock.json, package.json, src/js/inject.js
_Saving BTD of its apparent doom_
=> :sparkles: update moduleRaid and use module jQuery if it's not found

src/js/inject.js
__IMPORTANT FIX IMPORTANT FIX IMPORTANT FIX IMPORTANT FIX IMPORTANT FIX IMPORTANT FIX__
=> :bug: Stricter search for jQuery

src/js/util/ame.js
This is a mute setting of reversed version of "Follower count greater than".
=> Add a new setting to mute "Follower count greater than"

src/js/content.js
That said it still not perfect...
Before|After
---|---
=> Fix alignement with latest TweetDeck release

.vscode/settings.json, src/_locales/en/messages.json, src/_locales/fr/messages.json, src/css/index.css, src/js/background.js, src/js/inject.js, src/options/options.html
=> Options for mute/block items in a tweet's actions bar

src/_locales/en/messages.json, src/_locales/ja/messages.json
Hello,
I updated Japanese localization about  mute & block shortcut buttons.
Also, I added a few missing strings into `_locales/en/messages.json` for the translation.
\# Thank you for your fix BetterTweetDeck for the recent change of TweetDeck! 😁
=> Update japanese localization

src/js/background.js, tools/manifests/common.js, tools/manifests/firefox.js
Fixes https://github.com/eramdam/BetterTweetDeck/issues/422
=> Modify TweetDeck's CSP to fix fetch errors

src/js/util/emojis/emojiCompletion.js, src/js/util/emojis/emojiUtils.js
Turns out I never really did fix the emoji insertion bug that happened when using the auto completion.
Also I made it so the emoji completion matching is case insensitive.
=> Fix emoji typeahead insertion

package-lock.json, package.json
=> Upgrade DOMPurify per Mozilla's notice

src/_locales/ja/messages.json
Added the Japanese translation in v4.
If you like it, please merge it.
=> Add Japanese translations

src/features/changeTimestampFormat.ts, src/features/gifModals.tsx, src/features/renderCardsInColumns.ts, src/features/renderMediaAndQuotedTweets.ts, src/features/useOriginalAspectRatio.ts, src/services/chirpHandler.ts, src/types/tweetdeckTypes.ts, tools/manifests/common.js
Hopefully fixes https://github.com/eramdam/BetterTweetDeck/issues/557
=> Fix memory leaks linked to the cards feature

src/features/modernOverlays.ts
=> Fix modern overlay triggered in the tweet list modal

src/_locales/en/messages.json, src/components/settings/menu/settingsGeneral.tsx, src/components/settings/settingsMenu.tsx, src/components/settings/settingsModal.tsx, src/components/settings/settingsStyles.ts, src/components/settings/settingsTweetContent.tsx, src/features/contentWarnings.css, src/features/contentWarnings.ts, src/inject.ts, src/types/btdSettingsTypes.ts, src/types/tweetdeckTypes.ts
This is a port of https://github.com/eramdam/BetterTweetDeck/pull/483 for the v4 codebase.
=> Add content warnings

src/features/redraftTweet.ts, src/helpers/tweetdeckHelpers.ts, src/types/tweetdeckTypes.ts
Should fix https://github.com/eramdam/BetterTweetDeck/issues/712
=> Try to re-insert alt text when re-drafting a tweet

src/_locales/en/messages.json, src/components/settings/menu/settingsTweetActions.tsx, src/features/addTweetActions.ts, src/types/btdSettingsTypes.ts
Should fix https://github.com/eramdam/BetterTweetDeck/issues/707
=> Setting for confirmation

src/features/addTweetActions.ts
Fixed download-media action in Activity (liked tweet)
=> Fix download-media action in Activity
