src/_locales/fr/messages.json
Saw this weirdly-looking paragraph in the French version
Fixed:
* HTML link to Paypal
* Typo in "pouvez"
=> Fixed typo and link

src/_locales/en/messages.json, src/css/features/collapse-dms.css, src/css/index.css, src/js/background.js, src/options/options.html
This feature adds the ability to collapse read direct messages, meaning only unread direct messages will have their full text (or preview) displayed.
The styling and positioning of the usernames and dates might look a bit off, but considering there might be changes to it very often over time it is more effort to keep the positioning accurate based on magic numbers than just keeping it the way it is, it's not off too much off anyway and people adjust to change rather quickly.
=> Add feature to collapse read direct messages

src/js/util/providers/index.js, src/js/util/providers/pixiv.js, src/js/util/providers/twipple.js, src/js/util/thumbnails.js
- [Pixiv](https://pixiv.net): Most popular Japanese fanart & illustration community like [DeviantArt](https://deviantart.com)
- [twipple](http://twipple.jp): Twitter client and image sharing service provided by BIGLOBE, a famous Japanese ISP
You can test thumbnail preview by searching "p.twpl.jp OR p.twipple.jp" or "#pixiv \<your favorite works>" on TweetDeck.
=> Add supports of Pixiv & twipple thumbnails

src/css/options/tokens.css
Someone probably forgot that `.token` is already used somewhere :P 
Fixes:
Back to this:
=> Fix settings dump styling

package.json, src/js/util/providers/index.js, src/js/util/providers/tinami.js, src/js/util/thumbnails.js
[TINAMI](https://tinami.com) is one of famous Japanese illustration community for fans of anime and comics like Pixiv.
To use TINAMI API, we need to get TINAMI API key. Could you make a request for TINAMI API? It\'s not difficult and I think it takes only a few minutes. Here is workflow needed:
1. Register to TINAMI.
2. Make a request for TINAMI API.
3. Edit `config/default.js` to add a given key to `Client.APIs.tinami`. That\'s all.
You can easily [register to TINAMI](http://www.tinami.com/login?lang=en) via Twitter account, and fill forms in [API Request Form](www.tinami.com/api/key/form).
I translated **API Request form** and **API Guideline** to English for your reference. Visit here: https://gist.github.com/shuuji3/a7185b39c5c73a2ddbeb54682b1f81c8
You can test TINAMI provider by …
=> add support of TINAMI

src/css/index.css
This pull request makes embedded content larger on smaller (<=720p) screens.
=> Make embeds larger on smaller screens

src/js/util/providers/gyazo.js, src/js/util/providers/index.js, src/js/util/thumbnails.js
[Gyazo](https://gyazo.com/en) is a screenshot and screenshot GIF sharing service.
Gyazo's API requires an access token. Cloud you get one [here](https://gyazo.com/api?lang=en)?
Test URLs (GIF screenshot of BTD's GIF preview):
- https://gyazo.com/5fc7cfdd3aa6bb36fd6ee7a93c0659d7
- https://gyazo.com/59916a38f8423b6622444ec7c3d7eb28
Or try search `gyazo.com`.
=> Add support of Gyazo

docs/extend/css-features.md, docs/extend/providers.md, docs/install.md
BetterTweetDeck is missing some documentation for people that might want to help extending the client with different features, etc. pp.
This Pull Request adds the first few pieces of documentation for installation and extending with CSS-only features and thumbnail providers.
If this feature is fine as-is, it can be merged, but it can also be edited and further commits can be added for more different documentation topics, if wanted!
=> WIP: Documentation

.eslintrc.js, src/css/embeds.css, src/css/index.css, src/js/content.js, src/js/inject.js, src/js/util/providers/instagram.js, src/js/util/templates.js, src/js/util/thumbnails.js
Embeds for anything except images are broken right now in the sense that they either display at the wrong size (https://github.com/eramdam/BetterTweetDeck/issues/138) or just doesn't even display correctly (like Instagram).
This PR fixes that by replacing the modal HTML with a custom one that uses Flexbox to automatically center and size everything correctly.
=> Fix iframe/video modals

src/js/inject.js
Without this, you always have to click on the text input after switching back from another application where you've copied something you intend to paste to your tweet.
=> Automatically focus on text input when the window gets focus

src/css/index.css, src/js/content.js
Some little fixes for the `.btd-settings-btn`:
* Reflect TD CSS classes changes
* Fix attribute typo (missing closing `"` for `class` attribute)
* Better button position
* Fix the nav top bar position (with `.with-nav-border-t`)
* Better `.column-navigator-overflow` limits
---
Before|After
---|---
=> Fix `btd-settings-btn` markup and integration

src/js/inject.js
This does not let you download media from tweets that contain quotes in a timeline, because on the mustache `{{#tweet.entities.media.length}}` we can't check `{{#tweet.quotedTweet}}` as well. This only works for retweets because retweets also populate `entities.media`. For quotes, only `entities.urls` are populated but this isn't reliable enough to use compared to `quotedTweet`.
I wouldn't know a good way to go about this without hacking things onto `TD.services.TwitterStatus`.
=> Allowed downloading quoted tweet media in the popout modal.

src/_locales/en/messages.json, src/css/features/collapse-columns.css, src/css/index.css, src/js/background.js, src/js/content.js, src/js/inject.js, src/options/options.html
Hide a column by clicking on `-` a lot.
Restore a column by clicking on it in the left column navigator.
notes:
* needs more work
* keyboard navigation `1-9` seems to work weirdly.
* if you minimize a column in the front, pressing `1` will take you
to the _new_ first available column
* if you minimize a column in the 4th position then it will
absorb keypresses as if it is still there
* the column heads show numbers, these are from CSS, therefore hiding
a column makes the styles skip numbers making it appear as if they
do not exist anywhere but the left navigation
* lots of styles could probably be shaved out but i'm bad at everything
not tested columns:
* any 'temporary' column (whatever those are)
* columns with long titles and/or usernames
* searches / trending / editable column titles …
=> Added hiding columns from the column header.

package.json
stop trying to pick fights with javascript we don't even use
the reason I used quotes was because we wanna use [node style globbing](https://eslint.org/docs/user-guide/command-line-interface) on windows
=> only run eslint on src, tools, config, and gulpfile

config/default.js, src/js/content.js
config-browserify wasn't letting the client files read things right and it was confusing and made me upset
***this should be merged in before the beta program goes live.**
fortunately, the existing beta builds that are based off the initial set of code will respond properly
the current beta build (3.4.5) responds to the version check fine, so you can test this code against the current beta build
=> allowed the extension_ids array to be read properly

config/default.js, src/js/inject.js
- `_BTD*` stuff scoped to `window.BTD.debug`
- firefox won't build without a dummy firefox id, added one
=> developer enhancements for in-browser debugging

src/_locales/en/messages.json, src/js/background.js, src/js/inject.js, src/options/options.html
modifications from source:
- fixed composer remaining numbers if at or above 280
- kept as close to the original source as eslint would allow
- fires with 'one', only does that if setting is enabled
notes:
- unnamed functions break if arrowed
- no-rest-args breaks if spread operator used
=> two hundred and eighty characters

src/js/inject.js
the reason twittercall fails was because `this` was messed up,
wrapping it still obscured `this`.
this code also only listens for relevant API endpoints, as opposed to
excluding purely retweets for the sake of safety.
=> makes 280 char wrap gooder

src/js/util/emojis.js
This PR adds support for completing shortcodes of emoji with tab (instead of just with the enter key).
**Example:**
`:smil` -> *TAB Press* -> 😃
Most Platforms (like WhatsApp and Telegram) support completing shortcodes with TAB, since it's easier when writing to reach for the tab key instead of the enter key. When I write a tweet and use a shortcode in it I automatically hit TAB for completing the emoji (because of my habits of WhatsApp and Telegram) which currently leads to a focus change onto the send button. That's a bit annoying.
=> Add support for completing emoji shortcodes with tabulator key

src/js/util/ame.js
Small PR to remove the formatting help for the user|keyword filter.
The placeholder explains it enough, I guess.
=> :wrench: remove formatting guide from name

src/_locales/en/messages.json, src/_locales/ja/messages.json, src/options/options.html
When there is no text in `src/_locales/en/messages.json` corresponding to a new text added to the setting file, all the following options fail to be translated into other languages.
=> Add locale texts for the "Re-enable Dark Theme" setting and update Japanese

src/js/util/providers/pixiv.js
In #303, it cannot get Pixiv thumbnail in this URL.
* https://www.pixiv.net/member_illust.php?id=3901537
=> Fix getting Pixiv thumbnail on user's page

src/_locales/ja/messages.json
Fix Japanese translation.
* `コラム` -> `カラム`
* `以前のスタイルに元に戻す` -> `以前のスタイルに戻す`
This PR will have no conflicts with #372
=> 🇯🇵 Fix Japanese translation

src/css/features/no-bg-modal.css
Expanding media overflows for small screens/windows e.g.
Issue seems to be with this:
https://github.com/eramdam/BetterTweetDeck/blob/6c97232780c8539d5ec4f8768a6094420830cf2f/src/css/features/no-bg-modal.css#L40
You can workaround it by adding this to your Custom CSS
html.btd-on .btd__no_bg_modal .med-embeditem{min-width:0px}
e.g.
=> Fix media overflow when using small windows

.gitignore
~~can't believe this is actually my first PR here~~
Found out that `.DS_Store` is not gitignored when cloning on my Macbook. This fixes it.
=> include `.DS_Store` in gitignore

docs/extend/providers.md, package-lock.json, package.json, src/js/content.js, src/js/util/providers/bandcamp.js, src/js/util/providers/pixiv.js, src/js/util/secureDomify.js, webpack.config.babel.js
I've been told that the favicon of TweetDeck changes whenever BTD parses the content of a Bandcamp page. While it seems to be inoffensive as no JS can be ran this way, it might cause other weird issues so I'm removing `domify` entirely and using DOMPurify everywhere I can to ensure no XSS is possible.
=> Remove domify to avoid favicon changing bug

src/js/inject.js
This implements @pixeldesu's trick to proxy the `getHogan` internal method in order to optionally grab our own modified mustache templates instead of the in-bundle one when possible.
Right now it seems safe but it might not be if the content of `TD.mustaches` and whatever is inside the modules start to drift apart but migration will be a hassle so I'll assume this stays safe for a while 🤞
=> Fix some templates not being replaced

src/_locales/cs/messages.json, src/_locales/de/messages.json, src/_locales/en/messages.json, src/_locales/fr/messages.json, src/_locales/ja/messages.json, src/js/background.js, src/js/inject.js, src/options/options.html
This PR adds timestamp templates to the download filename and enables to embed the date and time of the tweet into the filename strings.
The introduced templates are following: 
`year`, `month`, `day`, `hours`, `minutes`, and `secods`.
Also, the default template is changed to include the date and time.
This fixes #414.
The date and time can be determined from the tweet ID unless the tweet is deleted. However, as the comment on #414 says, it's better to include tweet date for the archiving purpose.
=> Add timestamp templates to the download filename

src/css/features/no-bg-modal.css
This fixes the "no background behind modal" option after TweetDeck's recent update that uses a regular html5 video player for videos.
And it's cleaner/simpler anyway.
=> Better, simpler and working CSS to remove the background in the modal

src/css/features/no-bg-modal.css, src/js/background.js, src/options/options.html, src/options/options.js, tools/manifests/common.js, tools/manifests/firefox.js
No more `tabs` permission ❌🚫 Better TweetDeck has progressed past the need for the `tabs` permission ❌🚫
=> Remove the need for the `tabs` permission

package-lock.json, package.json, src/js/content.js, src/js/inject.js
Fix #505
For some reason `file-saver` doesn't pass the right filename on Firefox 81, this fix creates a new File object with our custom name instead of relying on whatever `file-saver` is supposed to do to rename the downloaded file.
=> Make sure to have the right filename when saving images/videos

src/js/inject.js
When there are multiple compose boxes opened, pasting an image from the clipboard does not always popout and add the image to the right tweet. First reported here https://github.com/MehediH/Tweeten/issues/207.
This can cause real problems for users: for example, if someone has a DM open and a tweet reply box open, pasting an image from the clipboard into the DM reply box actually adds it to the tweet. 
This PR fixes it by getting the correct compose box instead of just adding it to the first one :)
=> Fix clipboard pasting

config/default.js, package-lock.json, package.json, src/options/options.js
I pushed a compiled version of the JS files by mistake and it had a GitHub token, and then I realized I could just, not use that token at all and still use the Github REST API instead of the GraphQL one 😅
=> Stop using apollo-fetch to render Changelog page

src/features/removeRedirection.ts, src/types/tweetdeckTypes.ts
Fixes #416.
Since the method `createUrlAnchor()` is not called when rendering the profile website link, I added template modification.
=> Remove t.co redirection even on profile website link

src/features/usernameDisplay.ts
This PR fixes the following issues:
- When "Name display style" is set to "Username only," screen names in DM conversation headers are displayed in duplicate.
- Notification/Activity columns show full names even if set to "Username only" or "Username and full name." (fixes #493)
Both of these issues seem to be caused by minor changes in mustache templates.
=> Fix usernames formatting issues

src/features/renderCardsInColumns.css, src/features/renderCardsInColumns.ts, src/inject.ts, src/services/columnMediaSizeMonitor.ts
Fixes https://github.com/eramdam/BetterTweetDeck/issues/615
This PR fixes the issue by specifying a min-height on the card containers.
=> Specify min-height on card containers to prevent scroll jumping

src/features/addAccentColors.css
_Self-explanatory quick fix._
`.compose-reply-tweet .tweet-body a` are the links inside tweet text you are replying to (the box above the composer) and I noticed the links weren't colored.
=> Color links in the compose reply box with the users accent color

src/components/settings/components/settingsCredits.tsx
I noticed that the contributors list links to the contributors’ API data, but it’s meant to return the human-viewable GitHub profile instead.
=> Changed links in contributors list from API responses to GitHub profiles

src/_locales/ja/messages.json
Hi, I append Japanese translations for `settings_mute_nfts_accounts`.
=> Add Japanese translations for settings_mute_nfts_accounts

src/helpers/domHelpers.tsx, tools/uploadNightly.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
=> Replace deprecated String.prototype.substr()

README.md
Sorry for another PR.😅  This is just a small fix for the "GitHub Workflow Status" badge on `README.md`. This error was introduced by the recent URL change of shields.io. You can read the details here: https://github.com/badges/shields/issues/8671.
**Before**
**After**
=> Fix CI badge error
